name: Run tests and package JAR artifacts with Maven

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - src/**
      - pom.xml

jobs:
  test:
    name: Run tests with JDK ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 14, 16, 17]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: zulu
          cache: maven
      - name: Test with Maven
        run: mvn -B test

  package:
    name: Package JAR artifacts
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
          cache: maven
      - name: Build with Maven
        run: mvn -B -Dmaven.test.skip package
      - name: Upload created artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar-packages
          path: target/*.jar
          if-no-files-found: error
